### ISSUE TITLE
What excel formulas does this project support?

### ISSUE THREAD

**Issue by ghost** [xem/sheet#10]
Hi - what excel formulas does this project support?

 If anyone can answer, I look forward to hearing from you.

**Comment by xem** [comment]
Hi,
All the browser's native Math properties and functions are supported, you can see a list here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math

**Comment by ghost** [comment]
@xem Hi. I thought it would be possible to have 500 excel formulas, something like this: https://exceljet.net/formulas

**Comment by xem** [comment]
Sorry, supporting all the Excel formulae was not the purpose of this micro app. The goal was just to achieve data storage + math in JS and in the smallest possible amount of bytes. The result should be seen as a toy more than a real productivity tool :)

**Comment by ghost** [comment]
@xem thank you for feedback. please close this issue now.
