### ISSUE TITLE
Downward/rightward references buggy

### ISSUE THREAD

**Issue by mmastrac** [xem/sheet#6]
If you create a downward or rightward reference in a cell, the reference will be broken if it refers to a formula cell. For example, set the following formulas/values in the first column of the example spreadsheet:

`A1`: =A2
`A2`: =A3
`A3`: =A4
`A4`: 1

Focus cell A3, then focus cell B3. You'll see a NaN appear in cell A2.

I tried modifying the `localStorage`- and labels-enabled version of the script to fix this issue (and also support recursive formulas properly) and the smallest I can get is 278 characters (up from 257):

```
<script>(o=b=>{for(j in a)for(i in a)y=a[i]+-~j,f=eval(y+`_=a=>${y}.value=eval("y.a"+l.${y}.replace(/[A-Z]\\d/g,'+$&_()')+"||[l.${y}]")`),b?document.write([["<p>"][i]]+y+`<input onfocus=value=[l[id]] onblur=l[id]=value,o() id=${y}> `):f()})(o(a="ABCD",l=localStorage))</script>
```

The fix for the other script versions may vary from this one - I haven't attempted to golf a fix there.

I've also used ES6 string-interpolation to save a few bytes. You could probably trim a few off the existing one using that technique.

**Comment by mmastrac** [comment]
276 bytes using one of the existing tricks:

```
<script>(o=b=>{for(j in a="ABCD")for(i in a)y=a[i]+-~j,f=eval(y+`_=a=>${y}.value=eval("y.a"+l.${y}.replace(/[A-Z]\\d/g,'+$&_()')+"||[l.${y}]")`),b?document.write([["<p>"][i]]+y+`<input onfocus=value=[l[id]] onblur=l[id]=value,o() id=${y}> `):f()})(o(l=localStorage))</script>
```

**Comment by xem** [comment]
Hello, and thanks a lot for your contribution!

as you can see in the homepage of the project, we saved 2 bytes by using better string logic (if I'm not mistaken, it uses the same trick as you do, ${y}), plus a factorization of "p" and "input".

I'm trying to analyze your edits and understand what you've done... and don't really get it yet. Could you please explain briefly how you fixed the cascading?

**Comment by mmastrac** [comment]
It may be clearer if I format this a bit. The big difference is that we're defining a function for each cell that can be used to "pull" the correct value for the cell from the other cells it references, while also setting its value.

```
<script>(o=b=>{for(j in a="ABCD")for(i in a)
y=a[i]+-~j,
f=eval(y+`_=a=>${y}.value=eval("y.a"+l.${y}.replace(/[A-Z]\\d/g,'+$&_()')+"||[l.${y}]")`),
b
    ?document.write([["<p>"][i]]+y+`<input onfocus=value=[l[id]] onblur=l[id]=value,o() id=${y}> `)
    :f()
})(o(l=localStorage))</script>
```

This is the line that both evaluates a cell from its formula/references and sets it current value:

```
f=eval(y+`_=a=>${y}.value=eval("y.a"+l.${y}.replace(/[A-Z]\\d/g,'+$&_()')+"||[l.${y}]")`),
```

It might be clearer to look at it with the eval expanded for cell `B2` (note that this is not necessarily going to compile):

```
f=eval(`B2_=a=>B2.value=eval("y.a"+l.B2.replace(/[A-Z]\\d/g,'+$&_()')+"||[l.B2]")`),
```

We end up with a function for each cell with a trailing underscore. For example, cell `B2` has a `B2_` function. This function, when evaluated, will dynamically evaluate the contents of that cell using a similar replace function to the one in the existing label/localStorage demo.

If we assume that B2 contains the formula `=B3+B4+2`, the inner eval gets expanded like so:

```
B2_=a=>B2.value=eval("y.a=B3_()+B4()+2||[l.B2]")
```

So when you call `B2_()`, this calculates the value of the cell from the current value of `B3` and `B4` (including references those cells might have!).

If B2 contains non-formula contents (eg: `123`), we end up with the following:

```
B2_=a=>B2.value=eval("y.a123||[l.B2]")
```

Because y will never have a property named `a123` the left side evaluates to `undefined` and B2.value is instead set to `[l.B2]` (the string contents of the cell).

**Comment by mmastrac** [comment]
I found a few bugs in the version above. I needed to add 11 bytes to fix two problems:

 1. If localStorage was empty it would crash
 2. Formulas that evaluated to zero wouldn't render zero properly

```
<script>(o=b=>{for(j in a="ABCD")for(i in a)y=a[i]+-~j,f=eval(y+`_=x=>(z=l.${y},${y}.value=(x=+eval(("y._"+z).replace(/[A-Z]\\d/g,'+$&_()')),x!=x?[z]:x))`),b?document.write([["<p>"][i]]+y+`<input onfocus=value=[l[id]] onblur=l[id]=value,o() id=${y}> `):f()})(o(l=localStorage))</script>
```

The function now looks like this:

```
f=eval(y+`_=x=>(z=l.${y},${y}.value=(x=+eval(("y._"+z).replace(/[A-Z]\\d/g,'+$&_()')),x!=x?[z]:x))`)
```

It now tests for NaN using `x!=x` instead of using the "truthy" test from before (`x||[z]`).

**Comment by xem** [comment]
Hi, and thanks a lot for all this work!

I'll need a bit of time to process all that honestly, but I'm very impressed.

Also, there's another issue I'm tryig to solve since this project exploded on Hacker News: it doesn't work well with decimal numbers (when you enter 2.5 in A1, on blur JS doesn't know what to do with eval("A1.value2.5"). Do you think the evolution you propose could handle this special case, maybe with a few tweaks?

Finally, would you like to join our JS golfing slack room? We're discussing this mini project (and others too) on http://jsgolf.club , we'd be happy to see you there. You can register using: http://register.jsgolf.club

Cheers!

**Comment by mmastrac** [comment]
Sure, I'll join the slack.

I struggled with the decimal problem too but I haven't figured out what to do. I'm pondering some sort of alternative eval but nothing seems feasible!

**Comment by xem** [comment]
I'm looking to replace the "+" by a "parseFloat()", but it's not enough
Cool, see you there!

**Comment by xem** [comment]
OH I finally got it, it's super clever!

**Comment by xem** [comment]
closing this issue as we nearly have a final version ;)
