### ISSUE TITLE
3,14

### ISSUE THREAD

**Issue by dataarchivist** [xem/sheet#9]
First: Its (again) a very impressive code.

So, I tested it with 
A1: 3,14
B1: 3,00
C1: =A1+B1

On "full with headers" it results in 3,143,00
On "minimal" it results in a NaN.
On "Full" it results in 3,143,00.

Its not really a bug, just my two cents. 
Keep up your impressive work! :)

**Comment by xem** [comment]
Hey!
Sorry about that, you need to use "." in floating point numbers, not ","
I know there are languages where "," is used as decimal separator, like "1 234,56" in french,
But in english, the comma is a thousands separator, and the dot is a decimal sparator: "1,234.56"
And in JavaScript (the language in which this app was coded), the decimal separator is also "." (ex: 1234.56)

**Comment by xem** [comment]
Oh, thanks a lot for the kind words! a whole team contributed to it :)

**Comment by dataarchivist** [comment]
Hey again, yeah this make sense. I tested it again and the results are now:
6.14000000000000**1** in full & full with headers. In minimal there are no results. 😄 

So, thanks to your impressive team, its always a nice time to surf into your code!

**Comment by xem** [comment]
Ah, that's another particularity of floating-point numbers in today's computers.
In 99% of programming languages (the ones relying on the underlying architecture), floating point addition is error prone. The most famous example is 0.1 + 0.2 != 0.3.
More info on: https://0.30000000000000004.com/
Sorry, not our fault :)

**Comment by xem** [comment]
(also, "minimal" only supports integers)

**Comment by dataarchivist** [comment]
Thanks again for the very helpful explaination! :)
